const Menu = [
  {
    id: 1,
    image: "images/aloo-pakora.jpg",
    name: "aloo pakoda",
    category: "lunch",
    price: "122",
    discription: "I love pakoda",
  },
  {
    id: 2,
    image: "images/chhola.jpeg",
    name: "chhola",
    category: "breakfast",
    price: "122",
    discription: "I love chhola",
  },
  {
    id: 3,
    image: "images/momo.jpeg",
    name: "momo",
    category: "lunch",
    price: "122",
    discription: "I love momo",
  },
  {
    id: 4,
    image: "images/rajmarice.jpeg",
    name: "rajmarice",
    category: "dinner",
    price: "122",
    discription: "I love rajma rice",
  },

  {
    id: 5,
    image: "images/corn.jpeg",
    name: "corn",
    category: "lunch",
    price: "122",
    discription: "I love corn",
  },
  {
    id: 6,
    image: "images/nonvegthali.jpeg",
    name: "non-veg thali",
    category: "dinner",
    price: "322",
    discription: "I love non-veg",
  },
  {
    id: 7,
    image: "images/paubhazi.jpeg",
    name: "paubhazi",
    category: "breakfast",
    price: "222",
    discription: "I love paubhazi",
  },
  {
    id: 8,
    image: "images/pizza.jpeg",
    name: "Pizza",
    category: "lunch",
    price: "1122",
    discription: "I love pizzza",
  },
  {
    id: 9,
    image: "images/puri.jpeg",
    name: "puri",
    category: "breakfast",
    price: "102",
    discription: "I love puri",
  },
  {
    id: 10,
    image: "images/rotiwithmeat.jpeg",
    name: "roti and meat",
    category: "dinner",
    price: "822",
    discription: "I love meat with roti",
  },
  {
    id: 11,
    image: "images/samosa.jpeg",
    name: "samosa",
    category: "lunch",
    price: "22",
    discription: "I love samosa",
  },
  {
    id: 12,
    image: "images/Sweets.jpg",
    name: "Sweets",
    category: "dinner",
    price: "222",
    discription: "I love Sweets",
  },
  {
    id: 13,
    image: "images/vegthali.jpeg",
    name: "vegthali",
    category: "breakfast",
    price: "1122",
    discription: "I love vegthali",
  },
];

export default Menu;
